# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/chao/geant4/PRadSim

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/chao/geant4/PRadSim

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chao/geant4/PRadSim/CMakeFiles /home/chao/geant4/PRadSim/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chao/geant4/PRadSim/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named B3

# Build rule for target.
B3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 B3
.PHONY : B3

# fast build rule for target.
B3/fast:
	$(MAKE) -f CMakeFiles/B3.dir/build.make CMakeFiles/B3.dir/build
.PHONY : B3/fast

#=============================================================================
# Target rules for targets named PRadSim

# Build rule for target.
PRadSim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PRadSim
.PHONY : PRadSim

# fast build rule for target.
PRadSim/fast:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/build
.PHONY : PRadSim/fast

PRadSim.o: PRadSim.cc.o

.PHONY : PRadSim.o

# target to build an object file
PRadSim.cc.o:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/PRadSim.cc.o
.PHONY : PRadSim.cc.o

PRadSim.i: PRadSim.cc.i

.PHONY : PRadSim.i

# target to preprocess a source file
PRadSim.cc.i:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/PRadSim.cc.i
.PHONY : PRadSim.cc.i

PRadSim.s: PRadSim.cc.s

.PHONY : PRadSim.s

# target to generate assembly for a file
PRadSim.cc.s:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/PRadSim.cc.s
.PHONY : PRadSim.cc.s

src/CalorimeterHit.o: src/CalorimeterHit.cc.o

.PHONY : src/CalorimeterHit.o

# target to build an object file
src/CalorimeterHit.cc.o:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/CalorimeterHit.cc.o
.PHONY : src/CalorimeterHit.cc.o

src/CalorimeterHit.i: src/CalorimeterHit.cc.i

.PHONY : src/CalorimeterHit.i

# target to preprocess a source file
src/CalorimeterHit.cc.i:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/CalorimeterHit.cc.i
.PHONY : src/CalorimeterHit.cc.i

src/CalorimeterHit.s: src/CalorimeterHit.cc.s

.PHONY : src/CalorimeterHit.s

# target to generate assembly for a file
src/CalorimeterHit.cc.s:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/CalorimeterHit.cc.s
.PHONY : src/CalorimeterHit.cc.s

src/CalorimeterParameterisation.o: src/CalorimeterParameterisation.cc.o

.PHONY : src/CalorimeterParameterisation.o

# target to build an object file
src/CalorimeterParameterisation.cc.o:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/CalorimeterParameterisation.cc.o
.PHONY : src/CalorimeterParameterisation.cc.o

src/CalorimeterParameterisation.i: src/CalorimeterParameterisation.cc.i

.PHONY : src/CalorimeterParameterisation.i

# target to preprocess a source file
src/CalorimeterParameterisation.cc.i:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/CalorimeterParameterisation.cc.i
.PHONY : src/CalorimeterParameterisation.cc.i

src/CalorimeterParameterisation.s: src/CalorimeterParameterisation.cc.s

.PHONY : src/CalorimeterParameterisation.s

# target to generate assembly for a file
src/CalorimeterParameterisation.cc.s:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/CalorimeterParameterisation.cc.s
.PHONY : src/CalorimeterParameterisation.cc.s

src/CalorimeterSD.o: src/CalorimeterSD.cc.o

.PHONY : src/CalorimeterSD.o

# target to build an object file
src/CalorimeterSD.cc.o:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/CalorimeterSD.cc.o
.PHONY : src/CalorimeterSD.cc.o

src/CalorimeterSD.i: src/CalorimeterSD.cc.i

.PHONY : src/CalorimeterSD.i

# target to preprocess a source file
src/CalorimeterSD.cc.i:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/CalorimeterSD.cc.i
.PHONY : src/CalorimeterSD.cc.i

src/CalorimeterSD.s: src/CalorimeterSD.cc.s

.PHONY : src/CalorimeterSD.s

# target to generate assembly for a file
src/CalorimeterSD.cc.s:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/CalorimeterSD.cc.s
.PHONY : src/CalorimeterSD.cc.s

src/DetectorConstruction.o: src/DetectorConstruction.cc.o

.PHONY : src/DetectorConstruction.o

# target to build an object file
src/DetectorConstruction.cc.o:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/DetectorConstruction.cc.o
.PHONY : src/DetectorConstruction.cc.o

src/DetectorConstruction.i: src/DetectorConstruction.cc.i

.PHONY : src/DetectorConstruction.i

# target to preprocess a source file
src/DetectorConstruction.cc.i:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/DetectorConstruction.cc.i
.PHONY : src/DetectorConstruction.cc.i

src/DetectorConstruction.s: src/DetectorConstruction.cc.s

.PHONY : src/DetectorConstruction.s

# target to generate assembly for a file
src/DetectorConstruction.cc.s:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/DetectorConstruction.cc.s
.PHONY : src/DetectorConstruction.cc.s

src/DetectorMessenger.o: src/DetectorMessenger.cc.o

.PHONY : src/DetectorMessenger.o

# target to build an object file
src/DetectorMessenger.cc.o:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/DetectorMessenger.cc.o
.PHONY : src/DetectorMessenger.cc.o

src/DetectorMessenger.i: src/DetectorMessenger.cc.i

.PHONY : src/DetectorMessenger.i

# target to preprocess a source file
src/DetectorMessenger.cc.i:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/DetectorMessenger.cc.i
.PHONY : src/DetectorMessenger.cc.i

src/DetectorMessenger.s: src/DetectorMessenger.cc.s

.PHONY : src/DetectorMessenger.s

# target to generate assembly for a file
src/DetectorMessenger.cc.s:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/DetectorMessenger.cc.s
.PHONY : src/DetectorMessenger.cc.s

src/EventAction.o: src/EventAction.cc.o

.PHONY : src/EventAction.o

# target to build an object file
src/EventAction.cc.o:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/EventAction.cc.o
.PHONY : src/EventAction.cc.o

src/EventAction.i: src/EventAction.cc.i

.PHONY : src/EventAction.i

# target to preprocess a source file
src/EventAction.cc.i:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/EventAction.cc.i
.PHONY : src/EventAction.cc.i

src/EventAction.s: src/EventAction.cc.s

.PHONY : src/EventAction.s

# target to generate assembly for a file
src/EventAction.cc.s:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/EventAction.cc.s
.PHONY : src/EventAction.cc.s

src/EventActionMessenger.o: src/EventActionMessenger.cc.o

.PHONY : src/EventActionMessenger.o

# target to build an object file
src/EventActionMessenger.cc.o:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/EventActionMessenger.cc.o
.PHONY : src/EventActionMessenger.cc.o

src/EventActionMessenger.i: src/EventActionMessenger.cc.i

.PHONY : src/EventActionMessenger.i

# target to preprocess a source file
src/EventActionMessenger.cc.i:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/EventActionMessenger.cc.i
.PHONY : src/EventActionMessenger.cc.i

src/EventActionMessenger.s: src/EventActionMessenger.cc.s

.PHONY : src/EventActionMessenger.s

# target to generate assembly for a file
src/EventActionMessenger.cc.s:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/EventActionMessenger.cc.s
.PHONY : src/EventActionMessenger.cc.s

src/LeadGlassPartParameterisation.o: src/LeadGlassPartParameterisation.cc.o

.PHONY : src/LeadGlassPartParameterisation.o

# target to build an object file
src/LeadGlassPartParameterisation.cc.o:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/LeadGlassPartParameterisation.cc.o
.PHONY : src/LeadGlassPartParameterisation.cc.o

src/LeadGlassPartParameterisation.i: src/LeadGlassPartParameterisation.cc.i

.PHONY : src/LeadGlassPartParameterisation.i

# target to preprocess a source file
src/LeadGlassPartParameterisation.cc.i:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/LeadGlassPartParameterisation.cc.i
.PHONY : src/LeadGlassPartParameterisation.cc.i

src/LeadGlassPartParameterisation.s: src/LeadGlassPartParameterisation.cc.s

.PHONY : src/LeadGlassPartParameterisation.s

# target to generate assembly for a file
src/LeadGlassPartParameterisation.cc.s:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/LeadGlassPartParameterisation.cc.s
.PHONY : src/LeadGlassPartParameterisation.cc.s

src/PhysicsList.o: src/PhysicsList.cc.o

.PHONY : src/PhysicsList.o

# target to build an object file
src/PhysicsList.cc.o:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/PhysicsList.cc.o
.PHONY : src/PhysicsList.cc.o

src/PhysicsList.i: src/PhysicsList.cc.i

.PHONY : src/PhysicsList.i

# target to preprocess a source file
src/PhysicsList.cc.i:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/PhysicsList.cc.i
.PHONY : src/PhysicsList.cc.i

src/PhysicsList.s: src/PhysicsList.cc.s

.PHONY : src/PhysicsList.s

# target to generate assembly for a file
src/PhysicsList.cc.s:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/PhysicsList.cc.s
.PHONY : src/PhysicsList.cc.s

src/PrimaryGeneratorAction.o: src/PrimaryGeneratorAction.cc.o

.PHONY : src/PrimaryGeneratorAction.o

# target to build an object file
src/PrimaryGeneratorAction.cc.o:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/PrimaryGeneratorAction.cc.o
.PHONY : src/PrimaryGeneratorAction.cc.o

src/PrimaryGeneratorAction.i: src/PrimaryGeneratorAction.cc.i

.PHONY : src/PrimaryGeneratorAction.i

# target to preprocess a source file
src/PrimaryGeneratorAction.cc.i:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/PrimaryGeneratorAction.cc.i
.PHONY : src/PrimaryGeneratorAction.cc.i

src/PrimaryGeneratorAction.s: src/PrimaryGeneratorAction.cc.s

.PHONY : src/PrimaryGeneratorAction.s

# target to generate assembly for a file
src/PrimaryGeneratorAction.cc.s:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/PrimaryGeneratorAction.cc.s
.PHONY : src/PrimaryGeneratorAction.cc.s

src/PrimaryGeneratorMessenger.o: src/PrimaryGeneratorMessenger.cc.o

.PHONY : src/PrimaryGeneratorMessenger.o

# target to build an object file
src/PrimaryGeneratorMessenger.cc.o:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/PrimaryGeneratorMessenger.cc.o
.PHONY : src/PrimaryGeneratorMessenger.cc.o

src/PrimaryGeneratorMessenger.i: src/PrimaryGeneratorMessenger.cc.i

.PHONY : src/PrimaryGeneratorMessenger.i

# target to preprocess a source file
src/PrimaryGeneratorMessenger.cc.i:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/PrimaryGeneratorMessenger.cc.i
.PHONY : src/PrimaryGeneratorMessenger.cc.i

src/PrimaryGeneratorMessenger.s: src/PrimaryGeneratorMessenger.cc.s

.PHONY : src/PrimaryGeneratorMessenger.s

# target to generate assembly for a file
src/PrimaryGeneratorMessenger.cc.s:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/PrimaryGeneratorMessenger.cc.s
.PHONY : src/PrimaryGeneratorMessenger.cc.s

src/RunAction.o: src/RunAction.cc.o

.PHONY : src/RunAction.o

# target to build an object file
src/RunAction.cc.o:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/RunAction.cc.o
.PHONY : src/RunAction.cc.o

src/RunAction.i: src/RunAction.cc.i

.PHONY : src/RunAction.i

# target to preprocess a source file
src/RunAction.cc.i:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/RunAction.cc.i
.PHONY : src/RunAction.cc.i

src/RunAction.s: src/RunAction.cc.s

.PHONY : src/RunAction.s

# target to generate assembly for a file
src/RunAction.cc.s:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/RunAction.cc.s
.PHONY : src/RunAction.cc.s

src/SteppingAction.o: src/SteppingAction.cc.o

.PHONY : src/SteppingAction.o

# target to build an object file
src/SteppingAction.cc.o:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/SteppingAction.cc.o
.PHONY : src/SteppingAction.cc.o

src/SteppingAction.i: src/SteppingAction.cc.i

.PHONY : src/SteppingAction.i

# target to preprocess a source file
src/SteppingAction.cc.i:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/SteppingAction.cc.i
.PHONY : src/SteppingAction.cc.i

src/SteppingAction.s: src/SteppingAction.cc.s

.PHONY : src/SteppingAction.s

# target to generate assembly for a file
src/SteppingAction.cc.s:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/SteppingAction.cc.s
.PHONY : src/SteppingAction.cc.s

src/SteppingVerbose.o: src/SteppingVerbose.cc.o

.PHONY : src/SteppingVerbose.o

# target to build an object file
src/SteppingVerbose.cc.o:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/SteppingVerbose.cc.o
.PHONY : src/SteppingVerbose.cc.o

src/SteppingVerbose.i: src/SteppingVerbose.cc.i

.PHONY : src/SteppingVerbose.i

# target to preprocess a source file
src/SteppingVerbose.cc.i:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/SteppingVerbose.cc.i
.PHONY : src/SteppingVerbose.cc.i

src/SteppingVerbose.s: src/SteppingVerbose.cc.s

.PHONY : src/SteppingVerbose.s

# target to generate assembly for a file
src/SteppingVerbose.cc.s:
	$(MAKE) -f CMakeFiles/PRadSim.dir/build.make CMakeFiles/PRadSim.dir/src/SteppingVerbose.cc.s
.PHONY : src/SteppingVerbose.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... B3"
	@echo "... PRadSim"
	@echo "... PRadSim.o"
	@echo "... PRadSim.i"
	@echo "... PRadSim.s"
	@echo "... src/CalorimeterHit.o"
	@echo "... src/CalorimeterHit.i"
	@echo "... src/CalorimeterHit.s"
	@echo "... src/CalorimeterParameterisation.o"
	@echo "... src/CalorimeterParameterisation.i"
	@echo "... src/CalorimeterParameterisation.s"
	@echo "... src/CalorimeterSD.o"
	@echo "... src/CalorimeterSD.i"
	@echo "... src/CalorimeterSD.s"
	@echo "... src/DetectorConstruction.o"
	@echo "... src/DetectorConstruction.i"
	@echo "... src/DetectorConstruction.s"
	@echo "... src/DetectorMessenger.o"
	@echo "... src/DetectorMessenger.i"
	@echo "... src/DetectorMessenger.s"
	@echo "... src/EventAction.o"
	@echo "... src/EventAction.i"
	@echo "... src/EventAction.s"
	@echo "... src/EventActionMessenger.o"
	@echo "... src/EventActionMessenger.i"
	@echo "... src/EventActionMessenger.s"
	@echo "... src/LeadGlassPartParameterisation.o"
	@echo "... src/LeadGlassPartParameterisation.i"
	@echo "... src/LeadGlassPartParameterisation.s"
	@echo "... src/PhysicsList.o"
	@echo "... src/PhysicsList.i"
	@echo "... src/PhysicsList.s"
	@echo "... src/PrimaryGeneratorAction.o"
	@echo "... src/PrimaryGeneratorAction.i"
	@echo "... src/PrimaryGeneratorAction.s"
	@echo "... src/PrimaryGeneratorMessenger.o"
	@echo "... src/PrimaryGeneratorMessenger.i"
	@echo "... src/PrimaryGeneratorMessenger.s"
	@echo "... src/RunAction.o"
	@echo "... src/RunAction.i"
	@echo "... src/RunAction.s"
	@echo "... src/SteppingAction.o"
	@echo "... src/SteppingAction.i"
	@echo "... src/SteppingAction.s"
	@echo "... src/SteppingVerbose.o"
	@echo "... src/SteppingVerbose.i"
	@echo "... src/SteppingVerbose.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

