      real W,Q2
      real csthcm,phicm,epsilon,e_hel,qv_mag_cm,ppi_mag_cm
      real nu,nu_cm,fkt,gamma_v
	  
      common /kinematics/w,q2,csthcm,phicm,epsilon,e_hel,
     1       qv_mag_cm,ppi_mag_cm,nu,nu_cm,fkt,gamma_v

      real m_p, m_pip, m_pi0           
      real pi, alpha              

      parameter(alpha = .729735e-02)
      parameter(pi    = 3.141592654)
      parameter(m_p   = .9382799)
      parameter(m_pi0 = .1349764)
      parameter(m_pip = .1395700)
